version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mi-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mi_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
